-- 현장 모바일 앱(pine-app-main)과 웹이 공유하는 테이블·Storage 를 만든다.
--
-- 배경
--   이 네 테이블은 조원 프로젝트(ukrdqbxvyrndfauzkmxv)에만 있고 우리 프로젝트에는
--   없었다. 그래서 웹은 예측·보고서만 우리 DB에서 읽고, 확진목·현장사진은 조원 DB를
--   바라보는 반쪽 구성이었다. 앱까지 붙이려면 한 프로젝트로 모아야 한다.
--
--   정의는 조원 프로젝트의 실제 스키마를 그대로 옮긴 것이다. 컬럼명·기본값·인덱스가
--   같아야 앱 코드(useSupabase.ts)와 웹 코드(App.tsx)를 고치지 않고 붙는다.
--
-- 연결 구조 (이 마이그레이션이 성립시키는 것)
--   앱 신고 등록        -> pine_records.id = 42
--   웹 확진 처리        -> confirmed_trees.source_report_id = '42'
--   앱 사진/음성 촬영   -> field_photos.related_record_id     = '42'
--                         field_voice_logs.related_record_id  = '42'
--   웹 확진목 타임라인  -> source_report_id 로 묶어서 표시
--
-- 참고
--   조원 프로젝트의 pine_records 에는 trg_auto_roboflow_analysis (AFTER INSERT) 트리거가
--   있지만 외부 연동에 의존하므로 여기서는 만들지 않는다. 없어도 앱·웹 동작에 지장 없다.
--   rag_documents 도 만들지 않는다. RAG는 웹 백엔드의 document_chunks 로 일원화한다.

-- ---------------------------------------------------------------------------
-- 1. 시민·현장 신고
-- ---------------------------------------------------------------------------
create table if not exists pine_records (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz not null default now(),

  latitude          double precision,
  longitude         double precision,
  image_url         text,
  status            text,
  phone_number      text,

  -- Roboflow 판독 결과 (앱이 채우거나 비워둔다)
  ai_probability    double precision,
  ai_label          text,
  ai_status         text default 'pending'::text,
  ai_analyzed_at    timestamptz,
  ai_error          text,

  -- 비로그인 신고자가 자기 신고만 조회할 때 쓰는 토큰 (앱 Tickets 화면)
  report_token      text,

  -- 웹 대시보드에서 확진 처리하면 'confirmed' 가 된다.
  -- 웹은 이 값이 null 이거나 'confirmed' 가 아닌 것만 "접수 대기"로 보여준다.
  dashboard_status  text
);

create unique index if not exists pine_records_report_token_key
  on pine_records (report_token) where report_token is not null;

-- ---------------------------------------------------------------------------
-- 2. 확진목
-- ---------------------------------------------------------------------------
create table if not exists confirmed_trees (
  id                text primary key,
  region            text not null,
  species           text not null default '소나무'::text,
  confirmed_date    date not null default current_date,
  status            text not null default '확진완료'::text,
  severity          text not null default '중'::text,
  x                 integer not null default 0,
  y                 integer not null default 0,
  inspector         text not null default '시민 제보'::text,
  timeline          jsonb not null default '[]'::jsonb,

  -- 이 확진목을 만든 pine_records.id. 앱이 올린 사진·음성을 여기로 묶는다.
  source_report_id  text,

  ai_probability    numeric,
  latitude          double precision,
  longitude         double precision,
  image_url         text,
  image_source      text,
  image_bucket      text,
  image_path        text,
  analysis_result   jsonb,

  created_at        timestamptz not null default now()
);

create unique index if not exists confirmed_trees_source_report_id_key
  on confirmed_trees (source_report_id);

-- ---------------------------------------------------------------------------
-- 3. 현장사진 (앱 FieldPhotoPanel -> Storage field-photos)
-- ---------------------------------------------------------------------------
create table if not exists field_photos (
  id                 bigint generated by default as identity primary key,
  work_mode          text not null,
  related_record_id  text,
  storage_path       text not null,
  latitude           double precision not null,
  longitude          double precision not null,
  altitude           double precision,
  captured_at        timestamptz not null default now(),
  uploader_id        uuid,
  note               text,
  created_at         timestamptz not null default now()
);

create index if not exists field_photos_related_record_id_idx
  on field_photos (related_record_id);

comment on column field_photos.work_mode is 'surveillance(예찰·조사) 또는 control(방제·시공)';

-- ---------------------------------------------------------------------------
-- 4. 음성 작업일지 (앱 FieldSttPanel -> Storage field-audio + STT)
-- ---------------------------------------------------------------------------
create table if not exists field_voice_logs (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz not null default now(),

  work_mode          text not null,
  related_record_id  text not null,

  storage_bucket     text not null default 'field-audio'::text,
  storage_path       text not null,
  mime_type          text,
  duration_seconds   double precision,

  transcript         text,
  stt_status         text not null default 'completed'::text,
  stt_error          text,

  latitude           double precision,
  longitude          double precision,
  captured_at        timestamptz not null default now(),
  uploader_id        uuid,
  note               text
);

create unique index if not exists field_voice_logs_storage_path_key
  on field_voice_logs (storage_path);
create index if not exists field_voice_logs_related_record_id_idx
  on field_voice_logs (related_record_id);
create index if not exists field_voice_logs_captured_at_idx
  on field_voice_logs (captured_at desc);

comment on column field_voice_logs.stt_status is 'processing / completed / error';

-- ---------------------------------------------------------------------------
-- RLS — 조원 프로젝트의 정책을 그대로 옮긴다 (시연용이라 anon 전면 허용)
-- ---------------------------------------------------------------------------
alter table pine_records     enable row level security;
alter table confirmed_trees  enable row level security;
alter table field_photos     enable row level security;
alter table field_voice_logs enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public'
                 and tablename='pine_records' and policyname='pine_records_select_demo') then
    create policy pine_records_select_demo on pine_records
      for select to anon, authenticated using (true);
    create policy pine_records_insert_demo on pine_records
      for insert to anon, authenticated with check (true);
    create policy pine_records_update_demo on pine_records
      for update to anon, authenticated using (true) with check (true);
    create policy pine_records_delete_demo on pine_records
      for delete to anon, authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public'
                 and tablename='confirmed_trees' and policyname='confirmed_trees_select') then
    create policy confirmed_trees_select on confirmed_trees
      for select to anon, authenticated using (true);
    create policy confirmed_trees_insert on confirmed_trees
      for insert to anon, authenticated with check (true);
    create policy confirmed_trees_update on confirmed_trees
      for update to anon, authenticated using (true) with check (true);
    create policy confirmed_trees_delete on confirmed_trees
      for delete to anon, authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public'
                 and tablename='field_photos' and policyname='field_photos_select') then
    create policy field_photos_select on field_photos
      for select to anon, authenticated using (true);
    create policy field_photos_insert on field_photos
      for insert to anon, authenticated with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public'
                 and tablename='field_voice_logs' and policyname='field_voice_logs_select') then
    create policy field_voice_logs_select on field_voice_logs
      for select to anon, authenticated using (true);
    create policy field_voice_logs_insert on field_voice_logs
      for insert to anon, authenticated with check (true);
    create policy field_voice_logs_update on field_voice_logs
      for update to anon, authenticated using (true) with check (true);
  end if;
end $$;

grant select, insert, update, delete on pine_records, confirmed_trees to anon, authenticated;
grant select, insert on field_photos to anon, authenticated;
grant select, insert, update on field_voice_logs to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Storage 버킷 — 앱이 이 이름으로 업로드한다. 없으면 업로드가 통째로 실패한다.
--   pine-images  : 신고 사진 (public URL 을 pine_records.image_url 에 저장)
--   field-photos : 현장사진
--   field-audio  : 음성 작업일지 원본
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values
  ('pine-images',  'pine-images',  true),
  ('field-photos', 'field-photos', true),
  ('field-audio',  'field-audio',  true)
on conflict (id) do nothing;

do $$
declare
  b text;
begin
  foreach b in array array['pine-images', 'field-photos', 'field-audio'] loop
    if not exists (
      select 1 from pg_policies
      where schemaname = 'storage' and tablename = 'objects'
        and policyname = b || '_all'
    ) then
      execute format(
        'create policy %I on storage.objects for all to anon, authenticated '
        'using (bucket_id = %L) with check (bucket_id = %L)',
        b || '_all', b, b
      );
    end if;
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Realtime — 웹이 pine_records / field_photos / field_voice_logs 를 구독한다.
-- ---------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array['pine_records', 'field_photos', 'field_voice_logs', 'confirmed_trees'] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname='supabase_realtime' and schemaname='public' and tablename=t
    ) then
      execute format('alter publication supabase_realtime add table %I', t);
    end if;
  end loop;
end $$;
